### PR TITLE
Remove MIT license

### PR DESCRIPTION
**Pull request by tyranron**
To be fully compliant with the upstream `tb_client` library, we're removing MIT licensing and leave the only Apache-2.0.

## Checkoff

To agree to the licensing terms, please comment with the following text on this PR (you can copy the text using the copy button on the right):

```
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.
```

Thank you very much!

Affected contributors:
- [x] @50U10FCA7 
- [x] @dyc3 
- [x] @jeffutter 
- [x] @tyranron
- [x] @zetanumbers

### CODE REVIEW

**Comment by tyranron** [comment]
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.

**Comment by 50U10FCA7** [comment]
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.

**Comment by dyc3** [comment]
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.

**Comment by jeffutter** [comment]
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.

**Comment by zetanumbers** [comment]
I license my contributions to the `tigerbeetle-rust/tigerbeetle-unofficial` repository under the Apache-2.0 license.

**Pull request merged**
