### PR TITLE
Use `derive_more` to avoid boilerplate in core definitions

### PR DESCRIPTION
**Pull request by 50U10FCA7**
Reduce boilerplate in `core` crate by using `derive_more` Cargo dependency.

### CODE REVIEW

**Comment by 50U10FCA7** [comment]
### FCM
```markdown
Use `derive_more` Cargo dependency to avoid boilerplate (#25)
```

**Comment by zetanumbers** [comment]
This PR is pretty much many stylistic changes like sorting match branches and + using derive macros from `derive_more` to automatically implement `Display` and `Error` traits. Code size reduction is -84 lines, which I don't think would justify adding an additional dependency and using proc macros, potentially increasing build times in various scenarios and download size. Also choice for `derive_more` is a bit strange as there's `thiserror` which has 3x times more downloads and which I has the maintainer that I am already aware of.

I think those changes are not substantiated and may contain some regressions.

**Comment by 50U10FCA7** [comment]
> Code size reduction is -84 lines, which I don't think would justify adding an additional dependency and using proc macros, potentially increasing build times in various scenarios and download size.

The main point is not to reduce code size, but to make maintenance of this crate a bit easy:
- make code more readable and maintainable by removing boilerplate impls;
- sort things alphabetically;
- structure imports.

> Also choice for `derive_more` is a bit strange as there's `thiserror` which has 3x times more downloads and which I has the maintainer that I am already aware of.

`thiserror` is designed to work with errors, but we also have cases like [1](https://github.com/tigerbeetle-rust/tigerbeetle-unofficial/pull/25/files#diff-1054bdb5a28fcd65b8bd8fc1a99a2117e30fbd4eae5b87a82d24a756291f5a3bL86), [2](https://github.com/tigerbeetle-rust/tigerbeetle-unofficial/pull/25/files#diff-10b185cfacc682569626f999c19e79c84dda8f1010538b70a08fea4b5baa1380L115), etc

**Comment by zetanumbers** [comment]
> make code more readable and maintainable by removing boilerplate impls;

Boilerplate code is definitionally the most readable code, i.e. containing little information, the code we pretty much expect to see. The only times it substantially hurts readability is when there is too much of it, which is not the case here as your changes only removes 80 lines. And, to be honest, this isn't the reason you did those changes. Did you struggle to understand it? No, *you just want the code to look pretty.*

> sort things alphabetically

How that helps maintability? So new pull requests have to make sure to sort everything? No.

> structure imports

Rustc source code has the same style of imports, but you imagine such a low hanging fruit for a change to increase maintability would be desirable. And again would it need to be manually ensured for every code change?

**Pull request closed without merging**
